spring:
  #profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://localhost:3306/foro_hud
    username: root
    password: 123456789
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
  port: 8081

api:
  security:
    secret: ${JWT_SECRET:586E3277255738782FA13F4428472B4B4625065563566B597073373676397924}
